services:
  backend:
    container_name: backend
    build:
      context: backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
